server:
  port: 8083

spring:
  application:
    name: reinput-notification-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/  
  instance:
    prefer-ip-address: true    
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
